"""Regression tests for the verified-treatment-example corpus generated by
`scripts/generate_verified_treatment_examples.py`.

Each accepted example carries a `_target_indication_id` field. Iterating
all `examples/patient_verified_*.json` we assert:
  - the engine produces at least one track,
  - the default indication matches the target,
  - the (disease, line, regimen) signature is unique among verified examples,
  - no warning contains `ref error`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from knowledge_base.engine import generate_plan


REPO_ROOT = Path(__file__).parent.parent
KB_ROOT = REPO_ROOT / "knowledge_base" / "hosted" / "content"
EXAMPLES = REPO_ROOT / "examples"


def _patient_files() -> list[Path]:
    return sorted(EXAMPLES.glob("patient_verified_*.json"))


def _load(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def patient_files() -> list[Path]:
    return _patient_files()


def test_verified_corpus_present(patient_files):
    """Ensure the generator has produced at least one verified example."""
    assert len(patient_files) > 0, "no patient_verified_*.json files found"


def test_verified_signatures_unique(patient_files):
    """Each (disease, line, regimen) signature appears at most once in
    the verified corpus — otherwise we are duplicating coverage."""
    seen: dict[tuple, str] = {}
    indications = _indications_index()
    for p in patient_files:
        patient = _load(p)
        target = patient.get("_target_indication_id")
        ind = indications.get(target)
        if ind is None:
            continue
        appl = ind.get("applicable_to") or {}
        sig = (
            appl.get("disease_id") or appl.get("disease"),
            int(appl.get("line_of_therapy") or 0),
            ind.get("recommended_regimen") or "",
        )
        assert sig not in seen, (
            f"Duplicate signature {sig} in {p.name} and {seen[sig]}"
        )
        seen[sig] = p.name


@pytest.mark.parametrize("patient_file", _patient_files(), ids=lambda p: p.name)
def test_verified_example_routes_to_target(patient_file):
    patient = _load(patient_file)
    target = patient.get("_target_indication_id")
    assert target, f"{patient_file.name}: missing _target_indication_id"
    result = generate_plan(patient, kb_root=KB_ROOT)

    # 1. Engine must materialize at least one track.
    assert result.plan is not None and result.plan.tracks, (
        f"{patient_file.name}: empty tracks · warnings={result.warnings}"
    )

    # 2. Default indication must match the target.
    assert result.default_indication_id == target, (
        f"{patient_file.name}: default={result.default_indication_id}, "
        f"expected={target}"
    )

    # 3. No ref errors among load warnings.
    for w in result.warnings:
        assert "ref error" not in w, (
            f"{patient_file.name}: ref error warning · {w}"
        )


def _indications_index() -> dict[str, dict]:
    import yaml
    out: dict[str, dict] = {}
    for p in (KB_ROOT / "indications").glob("*.yaml"):
        d = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        if isinstance(d, dict) and d.get("id"):
            out[d["id"]] = d
    return out
