"""Backfill `category:` field on all RedFlag YAMLs.

For RFs generated by fill_*_priority_scaffolds.py the category is encoded
in the filename suffix; for legacy active RFs we use a hand-curated
mapping; for universal RFs we set per their semantic.

Idempotent: skips files that already have a `category:` line.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
RF_DIR = REPO_ROOT / "knowledge_base" / "hosted" / "content" / "redflags"

# Filename-suffix → category. Covers all 75 scaffold-derived files +
# many of the active originals.
SUFFIX_MAP: list[tuple[str, str]] = [
    ("_organ_dysfunction.yaml", "organ-dysfunction"),
    ("_infection_screening.yaml", "infection-screening"),
    ("_high_risk_biology.yaml", "high-risk-biology"),
    ("_transformation_progression.yaml", "transformation-progression"),
    ("_frailty_age.yaml", "frailty-age"),
]

# Hand-curated mapping for active RFs whose filenames don't match the
# 5-type suffix pattern.
EXPLICIT_MAP: dict[str, str] = {
    "rf_aggressive_histology_transformation.yaml": "transformation-progression",
    "rf_aitl_autoimmune_cytopenia.yaml": "high-risk-biology",
    "rf_aitl_ebv_driven_b_cell.yaml": "high-risk-biology",
    "rf_aitl_hypogamma.yaml": "infection-screening",
    "rf_bulky_disease.yaml": "high-risk-biology",
    "rf_burkitt_high_risk.yaml": "high-risk-biology",
    "rf_chl_advanced_stage.yaml": "high-risk-biology",
    "rf_cll_high_risk.yaml": "high-risk-biology",
    "rf_decomp_cirrhosis.yaml": "organ-dysfunction",
    "rf_dlbcl_cns_risk.yaml": "high-risk-biology",
    "rf_dlbcl_high_ipi.yaml": "high-risk-biology",
    "rf_fl_high_tumor_burden_gelf.yaml": "high-risk-biology",
    "rf_fl_transformation_suspect.yaml": "transformation-progression",
    "rf_hbv_coinfection.yaml": "infection-screening",
    "rf_mcl_blastoid_or_tp53.yaml": "high-risk-biology",
    "rf_mf_large_cell_transformation.yaml": "transformation-progression",
    "rf_mf_sezary_leukemic.yaml": "high-risk-biology",
    "rf_mm_high_risk_cytogenetics.yaml": "high-risk-biology",
    "rf_mm_renal_dysfunction.yaml": "organ-dysfunction",
    "rf_tcell_cd30_positive.yaml": "high-risk-biology",
    "rf_wm_hyperviscosity.yaml": "organ-dysfunction",
    # universal/
    "rf_universal_hbv_reactivation_risk.yaml": "infection-screening",
    "rf_universal_tls_risk.yaml": "organ-dysfunction",
    "rf_universal_infusion_reaction_first_cycle.yaml": "other",
}


_HAS_CATEGORY = re.compile(r"^category:\s*\S", re.MULTILINE)


def category_for(path: Path) -> str | None:
    name = path.name
    if name in EXPLICIT_MAP:
        return EXPLICIT_MAP[name]
    for suffix, cat in SUFFIX_MAP:
        if name.endswith(suffix):
            return cat
    return None


def insert_category(text: str, category: str) -> str:
    """Insert `category: <value>` into the YAML right after `priority:` line.
    Falls back to inserting before `relevant_diseases:` if no priority line."""
    lines = text.split("\n")
    insert_idx = None
    for i, line in enumerate(lines):
        if line.startswith("priority:"):
            insert_idx = i + 1
            break
    if insert_idx is None:
        for i, line in enumerate(lines):
            if line.startswith("relevant_diseases:"):
                insert_idx = i
                break
    if insert_idx is None:
        # Append before the trailing blank
        insert_idx = len(lines)
    lines.insert(insert_idx, f"category: {category}")
    return "\n".join(lines)


def main() -> int:
    edited = 0
    skipped_existing = 0
    skipped_unknown = 0
    for p in sorted(RF_DIR.rglob("*.yaml")):
        text = p.read_text(encoding="utf-8")
        if _HAS_CATEGORY.search(text):
            skipped_existing += 1
            continue
        cat = category_for(p)
        if cat is None:
            print(f"UNKNOWN: {p.name} — add to EXPLICIT_MAP", file=sys.stderr)
            skipped_unknown += 1
            continue
        new_text = insert_category(text, cat)
        p.write_text(new_text, encoding="utf-8")
        edited += 1
        print(f"set category={cat:30s} {p.name}")

    print(
        f"\nDone. Edited {edited}, "
        f"skipped {skipped_existing} (already had), "
        f"{skipped_unknown} (unknown — manual fix needed)."
    )
    return 1 if skipped_unknown else 0


if __name__ == "__main__":
    sys.exit(main())
